disabled_rules:
  - trailing_whitespace
identifier_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 45
    error: 60
type_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 45
    error: 60
