name: SwiftUICoordinator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - name: Select Xcode
    - uses: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer