name: SwiftUICoordinator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      PROJECT: Example/SwiftUICoordinatorExample/SwiftUICoordinatorExample.xcodeproj
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      SCHEME: SwiftUICoordinator
      DESTINATION: platform=iOS Simulator,name=iPhone 14
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select --switch $DEVELOPER_DIR
    - name: Clear Derived Data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
    - name: Build
      run: |
        swift package update
        xcodebuild clean build -scheme $SCHEME -destination "$DESTINATION"
  
  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          xcodebuild test -scheme $SCHEME -destination "$DESTINATION"
