name: SwiftUICoordinator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    - name: Build
      run: |
        brew update
        swift package update
        xcodebuild -workspace Example/SwiftUICoordinatorExample.xcworkspace -scheme SwiftUICoordinatorExample -destination 'platform=iOS Simulator,name=iPhone 11' clean build